name: python_lint

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.x
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: |
          # fail if there are any flake8 errors
          flake8 . --count --max-complexity=15 --max-line-length=127 --statistics

      - name: Check if 'Lint with flake8' step failed
        if: steps.flake8.outcome != 'success'
        run: |
          echo "flake8 fails"
          exit 1

  black_lint:
    runs-on: ubuntu-latest
    steps:
        - name: Setup
          uses: actions/checkout@v2
        - name: Install black in jupyter
          run: pip install black[jupyter]
        - name: Check code lints with Black
          uses: psf/black@stable
